[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hackerspace-gent-admin"
authors = [{name = "TQ Hirsch", email = "thequux@thequux.com"}]
dynamic = ["version", "description"]
